version: '3'
services:

  db:
    image: 'mongo:5.0'
    restart: unless-stopped
    networks:
      - internal
    environment:
      - MONGO_INITDB_DATABASE=nsdb
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build:
      context: cgm-remote-monitor
    environment:
      - API_SECRET=${API_SECRET}
      - MONGODB_URI=mongodb://nsdb:${DB_PASSWORD}@db/nsdb
      - PORT=1337
      - AUTH_DEFAULT_ROLES=denied

      # these are only needed when not behind https proxy
      - INSECURE_USE_HTTP=true
      - SECURE_HSTS_HEADER=false

    restart: unless-stopped
    networks:
      - web
      - internal
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 1338:1337

volumes:
  mongodata:

networks:
  internal:
  web:
    external: true
